# Generated by Django 2.2.2 on 2019-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_practice_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='manu',
            field=models.TextField(blank=True),
        ),
    ]
