# Generated by Django 2.2.3 on 2019-07-09 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190709_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
