# Generated by Django 2.2.3 on 2019-07-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190709_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
