# Generated by Django 2.2.3 on 2019-07-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_attend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=150, null=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Part', verbose_name='所属'),
        ),
    ]
