# Generated by Django 2.2.3 on 2019-07-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190709_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_attend',
            old_name='check',
            new_name='check_attend',
        ),
    ]
