# Generated by Django 2.2.3 on 2019-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190709_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
