# Generated by Django 2.2.3 on 2019-07-11 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190710_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='check_attend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_attend_field', to='app.Check_attend'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_field', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attend',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_field', to='app.Practice'),
        ),
    ]
