# Generated by Django 2.2.2 on 2019-06-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_atted_person_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='Place_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Place'),
            preserve_default=False,
        ),
    ]
